### PR TITLE
fix: Take related events into account for hash generation

### LINKED ISSUE #113: Review identity hash generation
2 findings on the screenshot have the same `identity_hash`  but different messages.
image

Needs investigation. One of the ideas by @dustinbyrne:
```
Maybe the hash should be generated from a unique set of all the related event's identity hashes as well?
```

### PR DESCRIPTION
**Pull request by torchello**
Fixes SCAN-173
Fixes #113

### CODE REVIEW

File: src/ruleChecker.ts [hunk 1]
```diff
@@ -148,6 +148,12 @@ export default class RuleChecker {
       const hash = createHash('sha256');
       hash.update(findingEvent.hash);
       hash.update(checkInstance.ruleId);
+      if (message) {
+        hash.update(message);
+      }
+      if (groupMessage) {
+        hash.update(groupMessage);
+      }
```
Comment (dustinbyrne) [inline src/ruleChecker.ts:156]: This will break our grouping of unique finding occurrences. Here are a few examples of how:
- https://github.com/applandinc/scanner/blob/main/src/rules/nPlusOneQuery.ts#L43
- https://github.com/applandinc/scanner/blob/main/src/rules/slowHttpServerRequest.ts#L12
- https://github.com/applandinc/scanner/blob/main/src/rules/secretInLog.ts#L44

**Review by dustinbyrne — CHANGES_REQUESTED** [review]

**Comment by kgilpin** [comment]
I’m not sure that using the message in the hash is a good idea. A message
is just meant to be a message.

**Comment by kgilpin** [comment]
If I change / adjust the message I wouldn’t expect that to break all the
hashes and invalidate all the deferred findings.

**Comment by dustinbyrne** [comment]
It may be enough to update the hash with a unique set of hashes from all of the `relatedEvents`. Is there a case that this would not be true?

**Comment by torchello** [comment]
> It may be enough to update the hash with a unique set of hashes from all of the relatedEvents. Is there a case that this would not be true?

I'll explore this option.

**Comment by torchello** [comment]
@dustinbyrne Using hashes of related events works well. Please have a look.

**Comment by torchello** [comment]
> Is this going to be too fragile for nPlusOneQuery and tooManyUpdates?

Do you mean cases where number of related events changes? I think it's fine from user perspective as a finding will be replaced by another finding (with a new hash). @dustinbyrne wdyt?

**Review by dustinbyrne — CHANGES_REQUESTED** [review]

**Review by dustinbyrne — APPROVED** [review]
